Update .env.local.example
workfloworchestrator/orchestrator-core-gui pull request #133
Opened 2022-06-23 10:14 UTC by acidjunk

#127 Update docs to avoid misleading info about websocket

2022-06-23 10:54 UTC, pboers1988 requested changes

2022-06-23 10:54 UTC, pboers1988 commented on .env.local.example
> +REACT_APP_BACKEND_URL="http://127.0.0.1:8000"
Port 8080 if I'm not mistaken.

2022-06-23 10:58 UTC, acidjunk commented on .env.local.example
> +REACT_APP_BACKEND_URL="http://127.0.0.1:8000"
Yes, mea culpa.

2022-06-23 10:59 UTC, acidjunk commented
We might change the names a bit to make it more clear. Previously the proxy would also handle request to backend for WS and normal API request. Now we direct them both straight to the backend as the old proxy solution had problems with CRA5

2022-07-04 07:16 UTC, pboers1988 approved these changes
LGTM

2022-07-04 07:16 UTC, merged